#!/usr/bin/env bash
# quick_verify_deepseek.sh — 用 DeepSeek 跑 quick_verify.sh，不改原脚本
#
# 1. 从 OpenClaw auth-profiles.json 读 DeepSeek key
# 2. 把它当作 ANTHROPIC_API_KEY 注入（shim 会拿来当 DeepSeek key 用）
# 3. 启用 sitecustomize 把 sys.modules['anthropic'] 替换成 _deepseek_shim
# 4. 透传所有参数给原 quick_verify.sh
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# 找 DeepSeek key
KEY_FILE="$HOME/.openclaw/agents/main/agent/auth-profiles.json"
if [ ! -f "$KEY_FILE" ]; then
  echo "✗ DeepSeek key 文件不存在：$KEY_FILE"
  echo "  请先 openclaw configure / 或 export DEEPSEEK_API_KEY=sk-..."
  exit 2
fi

DS_KEY=$(python3 -c "import json; print(json.load(open('$KEY_FILE'))['profiles']['deepseek:default']['key'])")
if [ -z "$DS_KEY" ]; then
  echo "✗ 在 $KEY_FILE 中找不到 profiles['deepseek:default'].key"
  exit 2
fi

# 也写一份临时 .env 文件让 quick_verify.sh 的 .env 加载逻辑通过（它会 set -a; source .env）
TMP_ENV=".env.deepseek-shim"
cat > "$TMP_ENV" << EOF
# auto-generated by quick_verify_deepseek.sh — DeepSeek 改造的临时 .env
ANTHROPIC_API_KEY=$DS_KEY
EOF

# 跑前清理可能存在的真 anthropic SDK 残留 import 缓存（无影响但干净）
rm -rf scripts/__pycache__ tests/__pycache__ 2>/dev/null || true

# 临时把 .env.deepseek-shim 链接成 .env（quick_verify.sh hardcode 读 .env）
LINKED_ENV=0
if [ ! -f .env ]; then
  ln -sf "$TMP_ENV" .env
  LINKED_ENV=1
fi

# 设置 shim 启用 + PYTHONPATH 让 sitecustomize 生效
export USE_DEEPSEEK_SHIM=1
export PYTHONPATH="$ROOT/scripts:${PYTHONPATH:-}"
export ANTHROPIC_API_KEY="$DS_KEY"

# 也确保 anthropic SDK 的 base_url 不冲突（防 anthropic SDK 真装了的情况）
unset ANTHROPIC_BASE_URL || true

echo "▶ DeepSeek shim 已启用 (key prefix: ${DS_KEY:0:8}***)"
echo "▶ PYTHONPATH=$PYTHONPATH"
echo "▶ 透传到 scripts/quick_verify.sh ..."
echo ""

# 跑原 quick_verify.sh，cleanup trap
cleanup() {
  if [ "$LINKED_ENV" = "1" ] && [ -L .env ]; then
    rm -f .env
  fi
  rm -f "$TMP_ENV"
}
trap cleanup EXIT

bash scripts/quick_verify.sh "$@"
